# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Publish Jar

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        type: 'string'
        default: 'main'
      mc_version:
        description: 'Minecraft Version'
        required: true
        type: 'string'
        default: '1.20.1'
      version:
        description: 'Version'
        required: true
        type: 'string'
        default: '1.0.0'
      version_type:
        description: 'Version Type'
        required: true
        type: 'choice'
        options:
          - 'alpha'
          - 'beta'
          - 'release'
        default: 'beta'
      publish_neoforge:
        description: 'Publish NeoForge'
        required: true
        type: 'boolean'
        default: true
      publish_fabric:
        description: 'Publish Fabric'
        required: true
        type: 'boolean'
        default: true
      publish_to_curseforge:
        description: 'Publish to CurseForge'
        required: true
        type: 'boolean'
        default: false
      publish_to_modrinth:
        description: 'Publish to Modrinth'
        required: true
        type: 'boolean'
        default: false
      publish_github_release:
        description: 'Publish GitHub Release'
        required: true
        type: 'boolean'
        default: true

env:
  JAVA_VERSION: 17

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          ref: ${{ inputs.branch }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew clean build -Pmod_version=${{inputs.version}}

      - name: Publish Fabric GitHub Release
        if: ${{ inputs.publish_fabric == true && inputs.publish_github_release == true }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: "${{secrets.PUBLISH_TOKEN}}"

          name: "${{inputs.mc_version}}+${{inputs.version}}-${{inputs.version_type}}"
          changelog-file: CHANGELOG.md
          files: fabric/build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar

          fail-mode: warn

      - name: Publish Fabric CurseForge
        if: ${{ inputs.publish_fabric == true && inputs.publish_to_curseforge == true }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 659897
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          name: "Fabric ${{inputs.mc_version}}+${{inputs.version}}-${{inputs.version_type}}"
          changelog-file: CHANGELOG.md
          files: fabric/build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar
          version-type: ${{inputs.version_type}}
          java: |
            Java 17
          game-versions: |
            ${{inputs.mc_version}}

          dependencies: |
            IrisShader(required){modrinth:iris}{curseforge:455508}
            CreateFabric(optional){modrithn:create-fabric}{curseforge:624165}

          fail-mode: warn

      - name: Publish Fabric Modrinth
        if: ${{ inputs.publish_fabric == true && inputs.publish_to_modrinth == true }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: iris-flw-compat
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          name: "Fabric ${{inputs.mc_version}}+${{inputs.version}}-${{inputs.version_type}}"
          changelog-file: CHANGELOG.md
          files: fabric/build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar
          version-type: ${{inputs.version_type}}
          java: |
            Java 17
          game-versions: |
            ${{inputs.mc_version}}

          dependencies: |
            IrisShader(required){modrinth:iris}{curseforge:455508}
            CreateFabric(optional){modrithn:create-fabric}{curseforge:624165}

          fail-mode: warn

      - name: Publish NeoForge GitHub Release
        if: ${{ inputs.publish_neoforge == true && inputs.publish_github_release == true }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: "${{secrets.PUBLISH_TOKEN}}"

          name: "${{inputs.mc_version}}+${{inputs.version}}-${{inputs.version_type}}"
          changelog-file: CHANGELOG.md
          files: neoforge/build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar
          version-type: ${{inputs.version_type}}

          fail-mode: warn

      - name: Publish NeoForge CurseForge
        if: ${{ inputs.publish_neoforge == true && inputs.publish_to_curseforge == true }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 659897
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          name: "NeoForge ${{inputs.mc_version}}+${{inputs.version}}-${{inputs.version_type}}"
          changelog-file: CHANGELOG.md
          files: neoforge/build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar
          version-type: ${{inputs.version_type}}
          java: |
            Java 17
          game-versions: |
            ${{inputs.mc_version}}

          dependencies: |
            IrisShader(required){modrinth:iris}{curseforge:455508}
            Create(optional){modrithn:create}{curseforge:328085}

          fail-mode: warn


      - name: Publish NeoForge Modrinth
        if: ${{ inputs.publish_neoforge == true && inputs.publish_to_modrinth == true }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: iris-flw-compat
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          name: "NeoForge ${{inputs.mc_version}}+${{inputs.version}}-${{inputs.version_type}}"
          changelog-file: CHANGELOG.md
          files: neoforge/build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar
          version-type: ${{inputs.version_type}}
          java: |
            Java 17
          game-versions: |
            ${{inputs.mc_version}}

          dependencies: |
            IrisShader(required){modrinth:iris}{curseforge:455508}
            Create(optional){modrithn:create}{curseforge:328085}

          fail-mode: warn